inclavare-containers/rats-tls

.clang-format
=> rats-tls: add .clang-format file

README.md
=> README: change the priority of sgx_ecdsa to High

README.md, docs/run_rats_tls_with_occlum.md
=> docs: reflect the corrent project path

README.md
=> README.md: remove centos8 related supporting

src/CMakeLists.txt, src/attesters/tdx-ecdsa/collect_evidence.c, src/include/rats-tls/api.h, src/include/rats-tls/cert.h, src/tls_wrappers/openssl/un_negotiate.c
Signed-off-by: liang3.yang@intel.com <Liang Yang>
=> rats-tls: add tdx event-log function

cmake/SGXSSL.cmake
Fixes: #72
Signed-off-by: Liang Yang <liang3.yang@intel.com>
=> rats-tls: compiling failure in SGX mode

docs/run_rats_tls_with_occlum.md
=> docs: update run rats tls with occlum steps

dist/Makefile, dist/rpm/rats_tls.spec.in
=> rats-tls/dist: add rpm support in anolis 8

.github/workflows/docker/Dockerfile-compilation-testing-anolis8.4
Signed-off-by: Sinuo Liu <984354607@qq.com>
=>     .github/workflows: add anolis 8.4 dockerfile for compilation testing

.github/workflows/docker/Dockerfile-compilation-testing-anolis8.4, .github/workflows/manually_compilation_testing_image.yml
Signed-off-by: Sinuo Liu <984354607@qq.com>
=> .github/workflows: add test images for compilation check

.github/workflows/pr_basic_compilation_check.yml
Signed-off-by: Sinuo Liu <984354607@qq.com>
=> .github/workflows: add compilation test of the source code

asn1/rats-tls.asn1
Signed-off-by: wangya <wangya.zs@alibaba-inc.com>
=> rats-tls: add the definition of rats-tls endorsement format in ASN.1

.github/workflows/docker/Dockerfile-compilation-testing-anolis8.4
Use 'ENV' to creating a global const for sgx SDK version.
Signed-off-by: Sinuo Liu <984354607@qq.com>
=> .github/workflows: set sgx sdk version macro

.github/workflows/docker/Dockerfile-compilation-testing-ubuntu20.04, .github/workflows/manually_compilation_testing_image.yml, .github/workflows/pr_basic_compilation_check.yml
Signed-off-by: Huiting Hou <houhuiting@stu.pku.edu.cn>
=> .github/workflows: support compile test image for ubuntu20.04

.github/workflows/manually_compilation_testing_image.yml
Signed-off-by: Huiting Hou <houhuiting@stu.pku.edu.cn>
=> .github/workflows: fix incorrect docker tag in compilation image

docs/run_rats_tls_with_occlum.md
=> docs: fix failed to complete RA by rats-tls with occlum mode in container

src/tls_wrappers/openssl/un_negotiate.c
fix https://github.com/inclavare-containers/rats-tls/issues/44
=> openssl/un_negotiate: fix verify evidence twice

src/crypto_wrappers/openssl/gen_cert.c
Fixed a bug that caused common extensions to be added multiple times to generated certificates. The bug was only present in epid mode.
=> openssl/gen_cert: fix adding common extension multiple times

src/include/edl/sgx_ecdsa.edl, src/sgx/untrust/sgx_ecdsa_ocall.c, src/verifiers/sgx-ecdsa/verify_evidence.c
Signed-off-by: Huiting Hou <houhuiting@stu.pku.edu.cn>
=> verifiers/sgx-ecdsa: fix the hash was not be compared in occlum mode

README.md
=> README: document the info about the listening port of sample server

src/attesters/csv/collect_evidence.c, src/attesters/internal/rtls_enclave_attester_select.c, src/attesters/sgx-ecdsa/collect_evidence.c, src/core/dice.c, src/core/rtls_core_generate_certificate.c, src/tls_wrappers/nulltls/use_privkey.c, src/tls_wrappers/openssl/un_negotiate.c, src/verifiers/internal/rtls_enclave_verifier_select.c, src/verifiers/nullverifier/cleanup.c, src/verifiers/sev/sev_utils.c, src/verifiers/sev/verify_evidence.c
=> Fix compile warnings about format strings

src/attesters/tdx-ecdsa/collect_evidence.c
=> attesters/tdx-ecdsa: allow userdata larger than 32 bytes

src/crypto_wrappers/openssl/gen_cert.c
=> openssl/gen_cert: fix cert to version 3 (0x2)

src/verifiers/sgx-ecdsa/verify_evidence.c
=> verifiers/sgx-ecdsa: fix memory leak in occlum mode

samples/rats-tls-server/server.c, samples/sgx-stub-enclave/sgx_stub_ecall.c, src/include/edl/rtls_socket.h
=> samples/rats-tls-server: add tcp keepalive option

.github/actions/generate-random-port/action.yml, .github/actions/generate-random-port/generate_port.sh, .github/workflows/tee_check.yml, README.md
null instance validation action, including some null instance combinations.
this is a basic version, random generate port would be used soon.
=> null instance action 
