inclavare-containers/rats-tls

src/attesters/CMakeLists.txt, src/core/cpu.c, src/verifiers/CMakeLists.txt
Fix the sgx build mode error as follows.
rats-tls/src/core/cpu.c:197:34: error: 'O_RDONLY' undeclared (first use in this function)
int fd = open("/dev/cpu/0/msr", O_RDONLY);
In addition, sev-snp attester and verifier are built only in host mode.
=> rats-tls: fix sgx build mode error

src/tls_wrappers/openssl/un_negotiate.c
The verbose error message is helpful to confirm the root
cause about pre-verification failure.
=> tls_wrappers/openssl: print verbose error about pre-verification failure

src/tls_wrappers/openssl/init.c
In order to let openssl work in all possible cases, enforce to use
TLSv1.2 protocol for openssl 1.0 build.
=> tls_wrappers/openssl: enforce to use tls 1.2 for openssl 1.0

README.md, src/attesters/csv/collect_evidence.c
KVM_HC_VM_ATTESTATION is one of the hypercall interface between csv
guest and KVM. Since linux upstream has introduced KVM_HC_MAP_GPA_RANGE
as 12, the current definition of KVM_HC_VM_ATTESTATION may invalid when
csv guest hosting on newer linux.
Define KVM_HC_VM_ATTESTATION as 100 to avoid conflicts with
KVM_HC_MAP_GPA_RANGE.
=> attesters/csv: Fix KVM_HC_VM_ATTESTATION to avoid potential conflicts

src/verifiers/sgx-ecdsa/verify_evidence.c
rats-tls/src/verifiers/sgx-ecdsa/verify_evidence.c:27:10: fatal error: sgx_dcap_ql_wrapper.h: No such file or directory
#include <sgx_dcap_ql_wrapper.h>
^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Fixes: #76
Signed-off-by: liang3.yang@intel.com <Liang Yang>
=> rats-tls: sovle a compiling issue casued by sgx header

src/core/main.c, src/core/rtls_common.c
sgx-ecdsa verifier can't be used in SGX mode. please
use sgx-ecdsa-qve instead.
Signed-off-by: Liang Yang <liang3.yang@intel.com>
=> rats-tls: add sgx-ecdsa attester in SGX mode

samples/rats-tls-client/client.c, samples/rats-tls-server/server.c
There are some improvements for the rats-tls samples code.
For the "client.c" file : 
```
char *const short_options = "a:v:t:c:ml:i:p:D:h";
//the following expression may be better: 
char *const short_options = "a:v:t:c:ml:i:p:DEh";
```
For the "server.c" file : 
```
char *const short_options = "a:v:t:c:ml:i:p:D:h";
//the following expression may be better:
char *const short_options = "a:v:t:c:ml:i:p:Dh";
```
=> rats-tls:fix spelling mistake in rats-tls sample code

src/core/cpu.c
This message is just for debug purpose. If current platform is not a SEV platform, this message printed in error manner is totally confused.
=> core/cpu.c: avoid printing error message during SEV platform detection

src/core/cpu.c
通过cpu厂商信息区分sev guest和csv guest
=> core/cpu: Distinguish cpu vendor when determine sev and csv support

CMakeLists.txt
Added a new option to CMakeLists.txt that enables the generation of compile_commands.json. This file can be used by IDEs and other tools to provide more accurate code completion and other features
=> CMakeLists.txt: enable generating compile_commands.json

src/api/rats_tls_receive.c, src/api/rats_tls_transmit.c, src/tls_wrappers/openssl/negotiate.c, src/tls_wrappers/openssl/un_negotiate.c
As a follow-up to PR #122, this commit addresses an issue where certificate extension verification was skipped when running in SGX mode, . It also fixes an error with the format string used in log prints.
=> openssl/un_negotiate: fix skipped cert verification in SGX mode

src/attesters/sgx-ecdsa/collect_evidence.c, src/attesters/sgx-la/collect_evidence.c
This pull request removes the restriction on `hash_len` in the sgx-ecdsa/sgx-la attester, which previously assumed that the incoming `hash_len` must be 32 bytes. However, due to the new interoperable RA-TLS cert proposal, the `pubkey-hash-value` embedded in the report is not a sha256 hash value, but a cbor structure with a size larger than 32 bytes. Therefore, this submission is intended to remove this restriction in order to support the new proposal.
=> attesters/sgx-ecdsa: fix sgx-ecdsa/sgx-la attesters to allow userdata larger than 32 bytes

.github/workflows/docker/Dockerfile-compilation-testing-anolis8.6, .github/workflows/manually_compilation_testing_image.yml, .github/workflows/pr_basic_compilation_check.yml
Use the sgx-linux release package of anolis 8.6 officially provided by intel to update the Anolis compilation test image.
=> .github/workflows: update compilation image to anolis 8.6

cmake/SGXSSL.cmake
This fix aims at addressing a broken setup of the rats-tls given that an old version of the Openssl library was used.
Signed-off-by: dzobbe <mazzeo.gio@gmail.com>
Signed-off-by: Huiting Hou <houhuiting@stu.pku.edu.cn>
=> Fix for SGX OpenSSL setup

src/attesters/sgx-ecdsa/collect_evidence.c
The `quote_size` is from outside the enclave. A malicious `quote_size` value would cause an out-of-bounds reading of data inside the enclave when call `ocall_qe_get_quote()`. Add this check to prevent this problem.
=> attesters/sgx-ecdsa: add check for quote_size

src/core/dice.c, src/core/rtls_core_generate_certificate.c, src/include/internal/dice.h, src/tls_wrappers/openssl/un_negotiate.c
The initial implementation of `evidence_buffer` has two forms. The first one is to put `<pubkey-hash>` into the userdata field of the evidence. The second is to put `<pubkey-hash>` into the claims_buffer.
This commit removes support for the first form, since it [has been deleted](https://github.com/CCC-Attestation/interoperable-ra-tls/blob/a2c2323377007aa27b5ceb453a741a860e0245a0/docs/Interoperable%20Attested%20TLS%5CInteroperable-RA-TLS-SGX-TDX-evidence-formats.md?plain=1#L22-L25) in the Interoperable RA-TLS proposal.
=> Unify the format of evidence_buffer

src/crypto_wrappers/openssl/gen_cert.c, src/tls_wrappers/openssl/un_negotiate.c
Mark evidence extensions as `non-critical`, since many TLS libraries (such as openssl or mbedtls) do not support extracting critical extensions.
See: https://github.com/CCC-Attestation/interoperable-ra-tls/issues/9
=> openssl/gen_cert: mark evidence extension as non-critical

src/attesters/csv/collect_evidence.c
This change fix spurious success if csv attester cannot get hsk_cek cert.
=> attester/csv: return non-zero value if failed to get hsk_cek cert

samples/sgx-stub-enclave/CMakeLists.txt, src/CMakeLists.txt, src/api/rats_tls_init.c, src/attesters/sgx-ecdsa/CMakeLists.txt, src/core/main.c, src/core/rtls_common.c, src/crypto_wrappers/internal/rtls_crypto_wrapper_load_single.c, src/crypto_wrappers/openssl/CMakeLists.txt, src/external/CMakeLists.txt, src/external/sgx-ssl/CMakeLists.txt, src/include/rats-tls/api.h, src/tls_wrappers/nulltls/CMakeLists.txt, src/tls_wrappers/nulltls/receive.c, src/tls_wrappers/nulltls/transmit.c, src/tls_wrappers/openssl/CMakeLists.txt, src/verifiers/sgx-ecdsa-qve/CMakeLists.txt, src/verifiers/sgx-ecdsa/CMakeLists.txt, src/verifiers/sgx-la/CMakeLists.txt
This commit strengthens the dependencies between different cmake tergets and makes multi-threaded compilation (`make -j`) work correctly.
=> CMakeLists.txt: fix include dirs and missing dependencies

samples/rats-tls-client/CMakeLists.txt, samples/rats-tls-server/CMakeLists.txt, src/CMakeLists.txt
Original header file directory: /usr/local/include/rats-tls/rats-tls/
Now the header file directory: /usr/local/include/rats-tls/
=> src/CMakeLists.txt: Fix header file directory error and missing claim.h

README.md
The CSV patches on Anolis supporting runtime attestation consist of [1](https://gitee.com/anolis/cloud-kernel/pulls/108) and [2](https://gitee.com/anolis/cloud-kernel/pulls/412). And main patch is the former while the latter only fixes a macro conflict.
=> add a link to CSV runtime attestation patches

src/core/dice.c
In some old version of libcbor (e.g. libcbor0.6 package from Ubuntu 20.04.5 LTS), the 3rd argument of `cbor_serialize_alloc()` [must be non-NULL](https://github.com/PJK/libcbor/blob/v0.6.0/src/cbor/serialization.c#L70).
=> Fix crash on older versions of libcbor

dist/rpm/rats-tls-filelist, dist/rpm/rats-tls-sgx-filelist
In https://github.com/inclavare-containers/rats-tls/pull/164, the header file directory changes to /usr/local/include/rats-tls/.
=> dist: fix error header file directory path

CMakeLists.txt, fuzz/CMakeLists.txt, fuzz/README.md, fuzz/tls_init/CMakeLists.txt, fuzz/tls_init/fuzz_init.cc, fuzz/tls_negotiate/CMakeLists.txt, fuzz/tls_negotiate/fuzz_negotiate.cc, fuzz/tls_server/CMakeLists.txt, fuzz/tls_server/fuzz_server.cc, fuzz/tls_transmit/CMakeLists.txt, fuzz/tls_transmit/fuzz_transmit.cc
use libfuzzer to fuzz rats-tls API `rats_tls_init()`, `rats_tls_negotiate()`,`rats_tls_transmit()` and
`rats_tls_receive()` in host mode
=> fuzz/*: fuzz rats-tls APIs in host mode
